# Workflow verifying project code style, using Flake8.
# (and setting line length to 100)

name: Flake8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  verify:
    name: Code verification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        flake8 . -v --count --max-line-length=100 --max-complexity=10 --per-file-ignores="__init__.py:F401" --show-source --statistics
